### ISSUE TITLE
Legion Update

### ISSUE THREAD

**Issue by Viciouss** [Eleadon/WoW-API-Libraries#1]
Hi, any chance this gets an update for Legion or maybe you could provide details on how this has been created? At least the profession sheet would be really helpful to me.

**Comment by siennathesane** [comment]
Most of this was from querying the API programmatically, you can find the docs here: https://dev.battle.net/

**Comment by Viciouss** [comment]
Unfortunately, the API doesn't provide anything related to the actual crafting process.  You can get the recipes for a character from the professions query and the provided recipe ids can be used to query for the name of the item that is produced by the recipe but that's it. No materials, material count, etc. which is what I'm in need of.

Seems like I have to write a small script to parse wowhead data for now but I'd prefer reading/extracting the data from a stable source like the wow client.
